name: Tests

on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches: [ "*" ]
jobs:
  django_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Run Django Tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          cd todo_app
          python manage.py test

